# Generated by Django 3.2.16 on 2022-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20221027_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('product', models.IntegerField()),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
