# Generated by Django 3.2.16 on 2022-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
