# Generated by Django 3.2.16 on 2022-10-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20221027_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='seller_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.admin'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100, null=True)),
                ('payable', models.FloatField()),
                ('paid', models.FloatField()),
                ('date', models.DateField()),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.buyer')),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.admin')),
            ],
        ),
    ]
