# Generated by Django 3.2.16 on 2022-10-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='seller_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.admin'),
        ),
    ]
