# Generated by Django 3.2.16 on 2022-10-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='seller_id',
            field=models.IntegerField(),
        ),
    ]
