# Generated by Django 3.2.16 on 2022-10-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_sale_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.buyer'),
        ),
    ]
