# Generated by Django 3.2.16 on 2022-10-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_sale_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.buyer'),
            preserve_default=False,
        ),
    ]
